### ISSUE TITLE
Martingale #18

### ISSUE THREAD

**Issue by Botman20000** [lmusarella/Pancakeswap-Prediction-Bot-2023#23]
Having a bug with Martingale mode on strategy with 3 dollar bets will run fine for a bit then will start skipping rounds saying waiting on martingale mode not really sure what caused it. Was working good then started having this bug I’ve tryed redownloading the file and starting over with new wallet new private key new rpc endpoint same thing. Something changed since yesterday also how can I send you a tip for your great work on this?

**Comment by lmusarella** [comment]
Hi, it's probably due to the fact that there are rounds that are eliminated. However, these rounds remain hanging and the bot considers them valid waiting in vain for the round to end. However, being an eliminated round it will never end, keeping the bot waiting. To resolve this for now you should reset the bot and restart it. As soon as I have some time, I will look into the matter further. I thought I already fixed it, but apparently I was wrong :(

If you want to help me you can simply star my repository!
